config/routes.rb
Rails.application.routes.draw do

  # Doorkeeper
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  # Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Search
  get '/search' => 'search#index', as: 'search'

  # sidekiq管理界面
  require 'sidekiq/web'
  authenticate :user, ->(u) { u.has_role? :admin} do
    mount Sidekiq::Web => '/sidekiq'
  end

  # 控制台
  namespace :admin do
    # 文章
    resources :topics

    # 图片
    resources :pictures
  end

  # 文章
  resources :topics, only: [:index, :show]

  resources :nodes, only: [:show]

  get 'notice' => 'notice#index'

  root to: "home#index"

  # API
  mount ApplicationAPI => '/api'
  mount GrapeSwaggerRails::Engine => '/docs'
end

app/models/topic.rb
class Topic < ApplicationRecord

  include Redis::Objects
  include MarkdownBody
  include SoftDelete
  include Searchable

  belongs_to :user, inverse_of: :topics
  belongs_to :node, inverse_of: :topics

  validates :user_id, :title, :body, presence: true

  # 不获取分类为'private'的文章
  scope :without_private, -> { joins(:node).where("nodes.name != 'private'") }

  # 阅读量
  counter :hits, default: 0

  before_create :init_last_active_mark_on_create
  def init_last_active_mark_on_create
    self.last_active_mark = Time.now.to_i
  end

  mapping do
    indexes :title
    indexes :body

    indexes :node do
      indexes :title, type: 'keyword'
    end
  end

  def as_indexed_json(options={})
    as_json(only: [:title, :body],
            include: { node: { only: :title }
            })
  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  load_and_authorize_resource

  def index
    if current_user.has_role?(:admin)
      # 获取全部的文章
      @topics = Topic.includes(:node).paginate(page: params[:page], per_page: 10).order('created_at DESC')
    else
      # 仅获取当前用户的文章
      user_id = current_user.id
      @topics = Topic.includes(:node).where("user_id in (:user_id)", user_id: user_id)
                  .paginate(page: params[:page], per_page: 10).order('created_at DESC')
    end
  end

  def show
    @topic = Topic.includes(:user).find(params[:id])

    render_404 if @topic.deleted?
  end

  def new
    @nodes_select = Node.all.collect { |node| [node.name, node.id] }
    @topic = Topic.new
  end

  def edit
    @nodes_select = Node.all.collect { |node| [node.name, node.id] }
    @topic = Topic.find_by_id(params[:id])
  end

  def create
    @nodes_select = Node.all.collect { |node| [node.name, node.id] }
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    if @topic.save
      redirect_to(admin_topic_path(@topic), notice: I18n.t('common.create_success'))
    else
      render action: 'new'
    end
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update_attributes(topic_params)
      redirect_to(admin_topic_path(@topic), notice: I18n.t('common.update_success'))
    else
      render action: 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to(admin_topics_path, notice: t('common.delete_success'))
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body, :node_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    # 只获取所有可见的文章信息
    node_ids = Node.where(publish: true).pluck(:id)

    @topics = Topic.includes(:node).where("node_id in (:node_ids)", node_ids: node_ids).paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def show
    @threads = []

    @topic = Topic.unscoped.includes(:user).find(params[:id])

    # 阅读量自动加1
    @threads << Thread.new do
      @topic.hits.incr(1)
    end

    @threads.each(&:join)

    render_404 if @topic.deleted?
  end

end

app/views/topics/_form.html.erb
<%= simple_form_for @topic, html: { class: "form form-horizontal" } do |f| %>
  <%= render "common/error_messages", target: @topic %>
  <div class="form-group">
    <div class="col-md-4">
      <%= f.select :node_id, options_for_select(@nodes_select, @topic.node_id), {}, {class: "form-control select_node"} %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :title, class: "form-control topic_title", placeholder: "在这里填写标题" %>
    </div>
  </div>

  <%#= render "editor_toolbar" %>

  <div class="form-group">
    <div class="col-md-12">
      <%= f.text_area :body, class: "topic-editor form-control closewarning", rows: 20 %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4">
      <%= f.submit t("common.save"), class: "btn btn-primary col-xs-2", 'data-disable-with' => t("common.saving") %>
    </div>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="topic media topic-<%= topic.id %>">
  <div class="infos media-body">
    <div class="title media-heading">
      <div class="row">
        <div class="col-md-10">
          <p>
            <span class="node"><%= topic.node.title %></span>
            <%= link_to(truncate(topic.title, length: 100), topic_path(topic), title: topic.title, :target=> "_blank") %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/_topic_info.html.erb
<div clas="panel-heading media clearfix"> 
  <div class="media-body">
    <h1 class="media-title"><%= topic.title %></h1>
    <div class="info">
      <%= topic.user.name %>
      ·
      <%= raw I18n.t("common.created_at", time: timeago(topic.created_at) )%>
      ·
      <%= topic.hits %> <%= I18n.t("common.read_times") %>

      <% if can? :edit, topic %>
        <%= link_to(I18n.t("common.editor_toolbar_edit"), edit_topic_path(@topic)) %>
      <% end %>
     </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="row">
  <div class="col-md-11">
    <div class="topic-detail panel panel-default">
      <div class="panel-heading">
        <%= render partial: "topics/topic_info", locals: { topic: @topic } %>
      </div>
      <div class="panel-body markdown">
        <article>
          <%= raw @topic.body_html %>
        </article>
      </div>
    </div>
  </div>
</div>