config/routes.rb
Rails.application.routes.draw do

  # Doorkeeper
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  # Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Search
  get '/search' => 'search#index', as: 'search'

  # sidekiq管理界面
  require 'sidekiq/web'
  authenticate :user, ->(u) { u.has_role? :admin} do
    mount Sidekiq::Web => '/sidekiq'
  end

  # 控制台
  namespace :admin do
    # 文章
    resources :topics

    # 图片
    resources :pictures
  end

  # 文章
  resources :topics, only: [:index, :show]

  resources :nodes, only: [:show]

  get 'notice' => 'notice#index'

  root to: "home#index"

  # API
  mount ApplicationAPI => '/api'
  mount GrapeSwaggerRails::Engine => '/docs'
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates_presence_of :image

  belongs_to :user

  # 图片
  mount_uploaders :image, AvatarUploader

  # # 删除时同时删除上传文件
  # after_destroy :delete_picture_file
  # def delete_picture_file
  #   FileUtils.remove_dir("#{Rails.root}/public/uploads/#{self.id}", :force => true) if self.image
  # end

end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < ApplicationController
  load_and_authorize_resource

  def index
    if current_user.has_role?(:admin)
      # 获取全部的图片
      @pictures = Picture.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    else
      # 仅获取当前用户的文章
      user_id = current_user.id
      @topics = Picture.includes(:node).where("user_id in (:user_id)", user_id: user_id)
                  .paginate(page: params[:page], per_page: 10).order('created_at DESC')
    end
  end

  def new
    @picture = Picture.new
  end

  def create
    # @picture = Picture.new(picture_params)
    # @picture.user_id = current_user.id

    # if @picture.save
    #   redirect_to(picture_path(@picture), notice: I18n.t('common.create_success'))
    # else
    #   render action: 'new'
    # end

    # 将上传的多张图片分别保存到一条记录中
    save_images = []
    params[:picture][:image].each do |i|
      image_info = { image: [i], user_id: current_user.id }
      save_images << image_info
    end

    if Picture.create(save_images)
      redirect_to(admin_pictures_path, notice: I18n.t('common.create_success'))
    else
      render action: 'new'
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to(admin_pictures_path, notice: t('common.delete_success'))
  end

  private

  def picture_params
    params.require(:picture).permit( {image: []} )
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  load_and_authorize_resource

  def index
    @pictures = Picture.paginate(page: params[:page], :per_page => 10).order('created_at DESC')
  end

  def new
    @picture = Picture.new
  end

  def create
    # @picture = Picture.new(picture_params)
    # @picture.user_id = current_user.id

    # if @picture.save
    #   redirect_to(picture_path(@picture), notice: I18n.t('common.create_success'))
    # else
    #   render action: 'new'
    # end

    # 将上传的多张图片分别保存到一条记录中
    save_images = []
    params[:picture][:image].each do |i|
      image_info = { image: [i], user_id: current_user.id }
      save_images << image_info
    end

    if Picture.create(save_images)
      redirect_to(pictures_path, notice: I18n.t('common.create_success'))
    else
      render action: 'new'
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to(pictures_path, notice: t('common.delete_success'))
  end

  private

  def picture_params
    params.require(:picture).permit( {image: []} )
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper

  # URL拷贝
  def image_url_copy(picture)
    url = picture.image.blank? ? '' : picture.image[0].url

    url_copy_html = ''
    url_copy_html += '<div class="input-group">'
    url_copy_html +=     '<input id="picture' + picture.id.to_s + '" value="' + url + '" type="text" class="form-control"/>'
    url_copy_html +=     '<span class="input-group-btn">'
    url_copy_html +=     '<button class="btn" data-clipboard-target="#picture' + picture.id.to_s + '">'
    url_copy_html +=         '拷贝URL'
    url_copy_html +=     '</button>'
    url_copy_html +=      '</span>'
    url_copy_html += '</div>'

    return raw(url_copy_html)
  end

end

app/views/admin/pictures/_form.html.erb
<%= simple_form_for [:admin, @picture], html: { class: "form" } do |f| %>
  <%= render "common/error_messages", target: @picture %>

  <div class="form-group">
    <%= f.file_field :image, multiple: true %>
  </div>

  <div class="form-group">
    <%= f.submit t("common.save"), class: "btn btn-primary col-xs-2", 'data-disable-with' => t("common.saving") %>
  </div>
<% end %>

app/views/admin/pictures/_picture.html.erb
<tr>
  <td>
    <img class="upload_picture" src="<%= picture.image[0].url %>" width = "60" height = "30" alt="图片名称" align=center />
  </td>
  <td>
    <%= image_url_copy(picture) %>
  </td>
  <% if can? :delete, picture %>
  <td>
    <%= link_to I18n.t("common.delete"), admin_picture_path(picture), method: 'DELETE', data: {confirm: I18n.t("common.confirm")}, class: "btn btn-sm btn-danger" %>
  </td>
  <% end %>
</tr>

<script type="text/javascript">
  var clipboard = new Clipboard(".btn");

  clipboard.on("success", function(e){
    console.info("Action :", e.action);
    console.info("Test :", e.text);
    console.info("Trigger :", e.trigger);

    e.clearSelection();
  });

  clipboard.on('error', function(e) {
    console.error('Action:', e.action);
    console.error('Trigger:', e.trigger);
  });
</script>

app/views/admin/pictures/index.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="pictures panel panel-default">
        <div class="panel-body">
          <% if @pictures.blank? %>
            <p>
              <span><%= I18n.t("common.empty_picture") %></span>
            </p>
          <% else %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <strong>图片列表</strong>
              </div>
              <table class="table table-striped table-hover">
                <tr>
                  <th>缩略图</th>
                  <th>图片URL</th>
                  <th>操作</th>
                </tr>
                <% cache(['pictures', @pictures]) do %>
                  <%= render @pictures %>
                <% end %>
              </table>
            </div>
          <% end %>
        </div>

        <%= will_paginate @pictures %>
    </div>
  </div>
</div>

app/views/admin/pictures/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong><%= I18n.t("common.create_picture") %></strong>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>