config/routes.rb
Rails.application.routes.draw do

  # Doorkeeper
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  # Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Search
  get '/search' => 'search#index', as: 'search'

  # sidekiq管理界面
  require 'sidekiq/web'
  authenticate :user, ->(u) { u.has_role? :admin} do
    mount Sidekiq::Web => '/sidekiq'
  end

  # 控制台
  namespace :admin do
    # 文章
    resources :topics

    # 图片
    resources :pictures
  end

  # 文章
  resources :topics, only: [:index, :show]

  resources :nodes, only: [:show]

  get 'notice' => 'notice#index'

  root to: "home#index"

  # API
  mount ApplicationAPI => '/api'
  mount GrapeSwaggerRails::Engine => '/docs'
end

app/views/common/_error_messages.html.erb
<% if target.errors.any? %>
 <div class="alert alert-block alert-danger">
   <a class="close" data-dismiss='alert' href="#">×</a>
   <p><strong>有 <%= target.errors.count %> 处问题导致无法提交:</strong></p>
   <ul>
   <% target.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav user-bar navbar-nav navbar-right">
  <% if current_user %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.login %><span class="caret"></span></a>
        <%= render_list class: "dropdown-menu", role: "menu" do |li|
          li << link_to(I18n.t("common.applications"), oauth_applications_path)
          li << link_to(I18n.t("common.logout"), destroy_user_session_path, method: "delete" )
        end %>
    </li>
  <% else %>
    <li><%= link_to( I18n.t("common.register"), new_user_registration_path) %></li>
    <li><%= link_to( I18n.t("common.login"), new_user_session_path ) %></li>
  <% end %>
</ul>

<% if current_user %>
  <ul class="nav navbar-nav create_bar navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-plus"></span><span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to(I18n.t("common.create_topic"), new_admin_topic_path) %></li>
        <li><%= link_to(I18n.t("common.create_picture"), new_admin_picture_path) %></li>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t("common.admin_control") %></span></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to I18n.t("common.topic_list"), admin_topics_path %></li>
        <li><%= link_to(I18n.t("common.picture_list"), admin_pictures_path) %></li>
      </ul>
    </li>
  </ul>
<% else %>
  <% # do nothing %>
<% end %>